In [0]:
#pip install --upgrade scikit-learn

In [0]:
from sklearn.feature_selection import mutual_info_classif
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from scipy.stats import chisquare
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
import csv
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

In [0]:
import matplotlib.pyplot as plt

In [0]:
from sklearn.metrics import f1_score

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import classification_report


In [7]:
from imblearn.over_sampling import SMOTE

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [7]:
from google.colab import drive 
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [0]:
d=pd.read_csv('gdrive/My Drive/Colab Notebooks/Predictive Modeling/Fraud/DATA/3. fraud_remove_nulls_fill_random_distribution/test-fraud_remove_nulls_fill_random_distribution.csv',compression='gzip')#2

In [11]:
d.head()

isFraud  TransactionAmt ProductCD  card1  card2  card3       card4  card5  card6  addr1  addr2  dist1    C1    C2   C3   C4    C5    C6   C7   C8    C9  C10   C11  C12   C13   C14     D1     D2     D3   D4     D5  D10   D11  D15 M1 M2 M3  M4 M5 M6 M7 M8 M9   V1   V2   V3   V4   V5   V6   V7   V8   V9  V10  V11  V12  V13  V14  V15  V16  V17  V18  V19  V20  V21  V22  V23  V24  V25  V26  V27  V28  V29  V30  V31  V32  V33  V34  V35  V36  V37  V38  V39  V40  V41  V42  V43  V44  V45  V46  V47  V48  V49  V50  V51  V52  V53  V54  V55  V56  V57  V58  V59  V60  V61  V62  V63  V64  V65  V66  V67  V68  V69  V70  V71  V72  V73  V74  V75  V76  V77  V78  V79  V80  V81  V82  V83  V84  V85  V86  V87  V88  V89  V90  V91  V92  V93  V94  V95  V96  V97  V98  V99  V100  V101  V102  V103  V104  V105  V106  V107  V108  V109  V110  V111  V112  V113  V114  V115  V116  V117  V118  V119  V120  V121  V122  V123  V124  V125   V126        V127        V128  V129        V130        V131   V132   V133   V134  \
0        0          189.95         W  13534  105.0  150.0        visa  226.0  debit  220.0   87.0   13.0   1.0   2.0  0.0  0.0   2.0   1.0  0.0  0.0   1.0  0.0   1.0  0.0   2.0   1.0    2.0    2.0    2.0  2.0    2.0  2.0  41.0  2.0  F  F  F  M2  F  F  F  F  T  0.0  2.0  2.0  2.0  0.0  2.0  2.0  2.0  2.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  2.0  0.0  0.0  0.0  0.0  1.0  1.0  2.0  2.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  2.0  0.0  0.0  0.0  1.0  1.0  2.0  2.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  2.0  0.0  0.0  0.0  0.0  1.0  1.0  2.0  2.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  2.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0    0.0   92.949997   92.949997   0.0   92.949997   92.949997    0.0    0.0    0.0   
1        0           27.95         W   4663  490.0  150.0        visa  166.0  debit  251.0   87.0   70.0  10.0  20.0  0.0  0.0  11.0  11.0  0.0  0.0  12.0  0.0  12.0  0.0  53.0  10.0    6.0    6.0    6.0  0.0   55.0  6.0   6.0  6.0  T  T  F  M2  F  F  F  F  F  1.0  1.0  1.0  1.0  2.0  1.0  1.0  1.0  1.0  1.0  2.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  2.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  2.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  2.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  2.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  2.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  2.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0    0.0  141.949997  141.949997   0.0  141.949997  141.949997    0.0    0.0    0.0   
2        0          407.50         W   8701  111.0  150.0        visa  226.0  debit  310.0   87.0   10.0   1.0   2.0  0.0  0.0   0.0   1.0  0.0  0.0   1.0  0.0   1.0  0.0   0.0   0.0    1.0  543.0    1.0  1.0    1.0  1.0   1.0  1.0  T  T  T  M1  F  F  F  T  T  1.0  2.0  2.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  2.0  2.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  2.0  2.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  2.0  2.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  2.0  2.0  2.0  0.0  0.0   0.0   2.0   2.0   2.0   0.0   0.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  961.5  961.500000  961.500000   0.0    0.000000    0.000000  961.5  961.5  961.5   
3        0         

In [12]:
d.select_dtypes(include=['object']).columns

Index(['ProductCD', 'card4', 'card6', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'id_12', 'id_15', 'id_16', 'id_28', 'id_29', 'id_31', 'id_35', 'id_36', 'id_37', 'id_38', 'DeviceType', 'P_emaildomain_bin', 'P_emaildomain_suffix', 'R_emaildomain_bin', 'R_emaildomain_suffix', 'device_name'], dtype='object')

In [13]:
len(d.select_dtypes(include=['object']).columns)

28

In [0]:
cat_cols=['ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6',
       'addr1', 'addr2', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9',
       'id_12', 'id_13', 'id_15', 'id_16', 'id_17', 'id_19', 'id_20', 'id_28',
       'id_29', 'id_31', 'id_35', 'id_36', 'id_37', 'id_38', 'DeviceType',
       '_Weekdays', '_Hours', '_Days', 'P_emaildomain_bin',
       'P_emaildomain_suffix', 'R_emaildomain_bin', 'R_emaildomain_suffix',
       'device_name', 'had_id', '_Month']

In [15]:
len(cat_cols)

43

In [0]:
for i in range(len(cat_cols)):
  col=cat_cols[i]
  d[col]=d[col].astype(str) 


In [71]:
print(d.select_dtypes(include=['object']))

       ProductCD  card1  card2  card3       card4  card5   card6  addr1 addr2 M1 M2 M3  M4 M5 M6 M7 M8 M9     id_12 id_13  id_15  id_16  id_17  id_19  id_20  id_28  id_29   id_31 id_35 id_36 id_37 id_38 DeviceType _Weekdays _Hours _Days P_emaildomain_bin P_emaildomain_suffix R_emaildomain_bin R_emaildomain_suffix device_name had_id _Month
0              W  13534  105.0  150.0        visa  226.0   debit  220.0  87.0  F  F  F  M2  F  F  F  F  T     Found  42.0  Found  Found  188.0  653.0  536.0    New  Found  Chrome     F     F     F     T    desktop         3     16    15             yahoo                  com             apple                  com     STELLAR      1      2
1              W   4663  490.0  150.0        visa  166.0   debit  251.0  87.0  T  T  F  M2  F  F  F  F  F     Found  42.0  Found  Found  188.0  653.0  536.0    New  Found  Chrome     F     F     F     T    desktop         2      0     2            google                  com             apple                  com    

In [17]:
len(d.select_dtypes(include=['object']).columns)

43

In [0]:
data=d

In [0]:
#To change file name uploaded
df_MI=pd.read_csv('gdrive/My Drive/Colab Notebooks/Predictive Modeling/Fraud/DATA/3. fraud_remove_nulls_fill_random_distribution/features_MI_train-remove_nulls_fill_random_distribution.csv')

In [0]:
features_25=data[list(df_MI['Column'].head(25))]
features_50=data[list(df_MI['Column'].head(50))]
features_75=data[list(df_MI['Column'].head(75))]
features_100=data[list(df_MI['Column'].head(100))]
features_150=data[list(df_MI['Column'].head(150))]
features_200=data[list(df_MI['Column'].head(200))]

In [21]:
features_25.shape

(177163, 25)

Spliting the data into features and target for isFraud=0 and isFraud=1

In [11]:
170964/6199

27.579286981771254

In [15]:
data_isFraud_1_indexes=list(data[data['isFraud']==1].index)
data_isFraud_0_indexes=list(data[data['isFraud']==0].index)
data_isFraud_1=data.iloc[data_isFraud_1_indexes , : ]
data_isFraud_0=data.iloc[data_isFraud_0_indexes , : ]

target_isFraud_1=data_isFraud_1['isFraud'].head(1000)
print('target_isFraurd_1 shape: ',target_isFraud_1.shape)

features_isFraud_1=data_isFraud_1.drop(['isFraud'],axis=1).head(1000)
print('features_isFraud_1 shape: ',features_isFraud_1.shape)

target_isFraud_0=data_isFraud_0['isFraud'].head(27500)
print('target_isFraurd_0 shape: ',target_isFraud_0.shape)

features_isFraud_0=data_isFraud_0.drop(['isFraud'],axis=1).head(27500)
print('features_isFraud_0 shape: ',features_isFraud_0.shape)

target_isFraurd_1 shape:  (1000,)
features_isFraud_1 shape:  (1000, 364)
target_isFraurd_0 shape:  (27500,)
features_isFraud_0 shape:  (27500, 364)


In [0]:
features_25_0=features_isFraud_0[list(df_MI['Column'].head(25))]
features_50_0=features_isFraud_0[list(df_MI['Column'].head(50))]
features_75_0=features_isFraud_0[list(df_MI['Column'].head(75))]
features_100_0=features_isFraud_0[list(df_MI['Column'].head(100))]
features_150_0=features_isFraud_0[list(df_MI['Column'].head(150))]
features_200_0=features_isFraud_0[list(df_MI['Column'].head(200))]

In [25]:
features_25_0.shape

(27500, 25)

In [0]:
features_25_1=features_isFraud_1[list(df_MI['Column'].head(25))]
features_50_1=features_isFraud_1[list(df_MI['Column'].head(50))]
features_75_1=features_isFraud_1[list(df_MI['Column'].head(75))]
features_100_1=features_isFraud_1[list(df_MI['Column'].head(100))]
features_150_1=features_isFraud_1[list(df_MI['Column'].head(150))]
features_200_1=features_isFraud_1[list(df_MI['Column'].head(200))]

In [15]:
features_25_1.shape

(1000, 25)

In [0]:
from sklearn.model_selection import KFold

In [0]:
def get_kfolds(splits,features,target):
  kf = KFold(n_splits=splits)

  X=features
  Y=target

  X_train_base=[]
  X_test_base=[]
  Y_train_base=[]
  Y_test_base=[]

  for train_index, test_index in kf.split(X):
      #print('train_index', train_index)
      #print('test_index', test_index)
      X_train, X_test = X.iloc[train_index,:], X.iloc[test_index,:]
      Y_train, Y_test = Y.iloc[train_index], Y.iloc[test_index]
      X_train_base.append(X_train)
      X_test_base.append(X_test)
      Y_train_base.append(Y_train)
      Y_test_base.append(Y_test)
  
  return(X_train_base,X_test_base,Y_train_base,Y_test_base)
  



In [82]:
to_dummy=d[cat_cols].nunique()[d[cat_cols].nunique()<10].index
len(to_dummy)

29

In [0]:
MI_TOP_0=[features_25_0,features_50_0,features_75_0,features_100_0,features_150_0,features_200_0]#,features_100_0,features_150_0,features_200_0


In [0]:
MI_TOP_1=[features_25_1,features_50_1,features_75_1,features_100_1,features_150_1,features_200_1]#,features_100_1,features_150_1,features_200_1


In [21]:
for i in range(len(MI_TOP_0)):
  print(MI_TOP_0[i].shape)
  category_cols=MI_TOP_0[i].select_dtypes(include=['object']).columns
  #category_cols=category_c.intersection(to_dummy)
  #to_drop=list(set(category_c) ^ set(category_cols))
  print(category_cols)
  MI_TOP_0[i] = pd.get_dummies(MI_TOP_0[i], columns=category_cols,drop_first=True)
  #MI_TOP_0[i].drop(MI_TOP_0[i].columns[to_drop], axis = 1, inplace = True)
  MI_TOP_1[i] = pd.get_dummies(MI_TOP_1[i], columns=category_cols,drop_first=True)
  #MI_TOP_1[i].drop(MI_TOP_1[i].columns[to_drop], axis = 1, inplace = True)
  print(MI_TOP_0[i].shape)
 

(27500, 25)
Index([], dtype='object')
(27500, 25)
(27500, 50)
Index([], dtype='object')
(27500, 50)
(27500, 75)
Index(['card1', 'card2'], dtype='object')
(27500, 4860)
(27500, 100)
Index(['card1', 'card2', 'id_19', 'id_20', 'id_17', 'addr1',
       'R_emaildomain_bin'],
      dtype='object')
(27500, 5494)
(27500, 150)
Index(['card1', 'card2', 'id_19', 'id_20', 'id_17', 'addr1',
       'R_emaildomain_bin', 'ProductCD', 'card3', 'addr2', 'id_13',
       'device_name'],
      dtype='object')
(27500, 5794)
(27500, 200)
Index(['card1', 'card2', 'id_19', 'id_20', 'id_17', 'addr1',
       'R_emaildomain_bin', 'ProductCD', 'card3', 'addr2', 'id_13',
       'device_name', 'id_28', 'id_12', 'id_37', 'card5', 'id_38'],
      dtype='object')
(27500, 5903)


In [92]:
for i in range(len(MI_TOP_0)):
  print(MI_TOP_0[i].isnull().sum().sum())
  print(MI_TOP_1[i].isnull().sum().sum())

0
0
0
0
0
0
0
0
0
0
0
0


In [98]:
train_features=[]
train_target=[]
test_features=[]
test_target=[]
i=0
X_train_0,X_test_0,Y_train_0,Y_test_0=get_kfolds(2,MI_TOP_0[i],target_isFraud_0)
X_train_1,X_test_1,Y_train_1,Y_test_1=get_kfolds(2,MI_TOP_1[i],target_isFraud_1)
for j in range(len(X_train_0)):
  tr_features = pd.concat([pd.DataFrame(X_train_0[j]), pd.DataFrame(X_train_1[j])], axis=0)
  tr_target = pd.concat([pd.DataFrame(Y_train_0[j]), pd.DataFrame(Y_train_1[j])], axis=0)
  te_features = pd.concat([pd.DataFrame(X_test_0[j]), pd.DataFrame(X_test_1[j])], axis=0)
  te_target = pd.concat([pd.DataFrame(Y_test_0[j]), pd.DataFrame(Y_test_1[j])], axis=0)
  X = np.array(tr_features)
  y = np.array(tr_target)
  sm = SMOTE(random_state=2)
  X_res, y_res = sm.fit_sample(X, y)
  #print("Number transactions X dataset: ", X.shape)
  #print("Number transactions y dataset: ", y.shape)
  #print("Number transactions X_res dataset: ", X_res.shape)
  #print("Number transactions y_res dataset: ", y_res.shape)
  #print("Before OverSampling, counts of label '1': {}".format(sum(y==1)))
  #print("Before OverSampling, counts of label '0': {} \n".format(sum(y==0)))
  #print("After OverSampling, counts of label '1': {}".format(sum(y_res==1)))
  #print("After OverSampling, counts of label '0': {} \n".format(sum(y_res==0)))
  train_features.append(X_res)
  train_target.append(y_res)
  X_te = np.array(te_features)
  y_te = np.array(te_target)

  
  test_features.append(X_te)
  test_target.append(y_te)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [99]:
model = LogisticRegression()  # Choose a model here
for i in range(len(train_features)):
   model.fit(train_features[i], train_target[i] )
   y_pred = model.predict(test_features[i])
   print(f'Number of TOP MI: {train_features[i].shape[1]}')
   print(f'Number fold: {i}')

   f_score=f1_score(test_target[i], y_pred)
   cm = metrics.confusion_matrix(test_target[i], y_pred)
   print(cm)

   print(f'f-score: {f_score}')

   print(classification_report(test_target[i], y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 25
Number fold: 0
[[10022  3728]
 [  196   304]]
f-score: 0.13415710503089143
              precision    recall  f1-score   support

           0       0.98      0.73      0.84     13750
           1       0.08      0.61      0.13       500

    accuracy                           0.72     14250
   macro avg       0.53      0.67      0.49     14250
weighted avg       0.95      0.72      0.81     14250



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 25
Number fold: 1
[[10222  3528]
 [  214   286]]
f-score: 0.13259156235512284
              precision    recall  f1-score   support

           0       0.98      0.74      0.85     13750
           1       0.07      0.57      0.13       500

    accuracy                           0.74     14250
   macro avg       0.53      0.66      0.49     14250
weighted avg       0.95      0.74      0.82     14250



In [45]:
train_features=[]
train_target=[]
test_features=[]
test_target=[]
i=1
X_train_0,X_test_0,Y_train_0,Y_test_0=get_kfolds(2,MI_TOP_0[i],target_isFraud_0)
X_train_1,X_test_1,Y_train_1,Y_test_1=get_kfolds(2,MI_TOP_1[i],target_isFraud_1)
for j in range(len(X_train_0)):
  tr_features = pd.concat([pd.DataFrame(X_train_0[j]), pd.DataFrame(X_train_1[j])], axis=0)
  tr_target = pd.concat([pd.DataFrame(Y_train_0[j]), pd.DataFrame(Y_train_1[j])], axis=0)
  te_features = pd.concat([pd.DataFrame(X_test_0[j]), pd.DataFrame(X_test_1[j])], axis=0)
  te_target = pd.concat([pd.DataFrame(Y_test_0[j]), pd.DataFrame(Y_test_1[j])], axis=0)
  X = np.array(tr_features)
  y = np.array(tr_target)
  sm = SMOTE(random_state=2)
  X_res, y_res = sm.fit_sample(X, y)
  #print("Number transactions X dataset: ", X.shape)
  #print("Number transactions y dataset: ", y.shape)
  #print("Number transactions X_res dataset: ", X_res.shape)
  #print("Number transactions y_res dataset: ", y_res.shape)
  #print("Before OverSampling, counts of label '1': {}".format(sum(y==1)))
  #print("Before OverSampling, counts of label '0': {} \n".format(sum(y==0)))
  #print("After OverSampling, counts of label '1': {}".format(sum(y_res==1)))
  #print("After OverSampling, counts of label '0': {} \n".format(sum(y_res==0)))
  train_features.append(X_res)
  train_target.append(y_res)
  X_te = np.array(te_features)
  y_te = np.array(te_target)

  
  test_features.append(X_te)
  test_target.append(y_te)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [46]:
model = LogisticRegression()  # Choose a model here
for i in range(len(train_features)):
   model.fit(train_features[i], train_target[i] )
   y_pred = model.predict(test_features[i])
   print(f'Number of TOP MI: {train_features[i].shape[1]}')
   print(f'Number fold: {i}')

   f_score=f1_score(test_target[i], y_pred)
   #cm = metrics.confusion_matrix(test_target[i], y_pred)
   #print(cm)

   print(f'f-score: {f_score}')

   print(classification_report(test_target[i], y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 50
Number fold: 0
f-score: 0.13897550111358575
              precision    recall  f1-score   support

           0       0.98      0.73      0.84     13750
           1       0.08      0.62      0.14       500

    accuracy                           0.73     14250
   macro avg       0.53      0.68      0.49     14250
weighted avg       0.95      0.73      0.81     14250



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 50
Number fold: 1
f-score: 0.13539470602014522
              precision    recall  f1-score   support

           0       0.98      0.75      0.85     13750
           1       0.08      0.58      0.14       500

    accuracy                           0.74     14250
   macro avg       0.53      0.66      0.49     14250
weighted avg       0.95      0.74      0.82     14250



In [100]:
train_features=[]
train_target=[]
test_features=[]
test_target=[]
i=2
print(MI_TOP_0[i].info())
X_train_0,X_test_0,Y_train_0,Y_test_0=get_kfolds(2,MI_TOP_0[i],target_isFraud_0)
X_train_1,X_test_1,Y_train_1,Y_test_1=get_kfolds(2,MI_TOP_1[i],target_isFraud_1)
for j in range(len(X_train_0)):
  tr_features = pd.concat([pd.DataFrame(X_train_0[j]), pd.DataFrame(X_train_1[j])], axis=0)
  tr_target = pd.concat([pd.DataFrame(Y_train_0[j]), pd.DataFrame(Y_train_1[j])], axis=0)
  te_features = pd.concat([pd.DataFrame(X_test_0[j]), pd.DataFrame(X_test_1[j])], axis=0)
  te_target = pd.concat([pd.DataFrame(Y_test_0[j]), pd.DataFrame(Y_test_1[j])], axis=0)
  
  y = np.array(tr_target)
  X = np.array(tr_features)
  X=np.any(np.isnan(X))
  X=np.all(np.isfinite(X))
  X=X.reshape(-1, 1)
  sm = SMOTE(random_state=2)
  X_res, y_res = sm.fit_sample(X, y)
  #print("Number transactions X dataset: ", X.shape)
  #print("Number transactions y dataset: ", y.shape)
  #print("Number transactions X_res dataset: ", X_res.shape)
  #print("Number transactions y_res dataset: ", y_res.shape)
  #print("Before OverSampling, counts of label '1': {}".format(sum(y==1)))
  #print("Before OverSampling, counts of label '0': {} \n".format(sum(y==0)))
  #print("After OverSampling, counts of label '1': {}".format(sum(y_res==1)))
  #print("After OverSampling, counts of label '0': {} \n".format(sum(y_res==0)))
  train_features.append(X_res)
  train_target.append(y_res)
  X_te = np.array(te_features)
  y_te = np.array(te_target)

  
  test_features.append(X_te)
  test_target.append(y_te)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27500 entries, 0 to 27499
Data columns (total 75 columns):
V123              27500 non-null float64
V125              27500 non-null float64
V249              27500 non-null float64
V290              27500 non-null float64
V124              27500 non-null float64
V191              27500 non-null float64
V196              27500 non-null float64
V193              27500 non-null float64
V247              27500 non-null float64
V192              27500 non-null float64
V23               27500 non-null float64
V86               27500 non-null float64
V26               27500 non-null float64
V292              27500 non-null float64
V188              27500 non-null float64
V189              27500 non-null float64
V252              27500 non-null float64
V244              27500 non-null float64
V186              27500 non-null float64
V242              27500 non-null float64
V200              27500 non-null float64
V190              27500 non-nu

TypeError: ignored

In [0]:
model = LogisticRegression()  # Choose a model here
for i in range(len(train_features)):
   model.fit(train_features[i], train_target[i] )
   y_pred = model.predict(test_features[i])
   print(f'Number of TOP MI: {train_features[i].shape[1]}')
   print(f'Number fold: {i}')

   f_score=f1_score(test_target[i], y_pred)
   #cm = metrics.confusion_matrix(test_target[i], y_pred)
   #print(cm)

   print(f'f-score: {f_score}')

   print(classification_report(test_target[i], y_pred))

In [0]:
for i in range(len(MI_TOP_0)):
  print(MI_TOP_0[i].head())

   V123  V125  V249  V290  V124  V191  ...  V242  V200  V190  V201  V87  V246
0   1.0   1.0  21.0   1.0   1.0   4.0  ...   2.0   2.0   2.0   2.0  1.0   2.0
1   1.0   1.0  21.0   1.0   1.0   4.0  ...   2.0   2.0   2.0   2.0  1.0   2.0
2   1.0   1.0  21.0   2.0   1.0   4.0  ...   2.0   2.0   2.0   2.0  1.0   2.0
3   1.0   1.0  21.0   1.0   1.0   4.0  ...   2.0   2.0   4.0   2.0  1.0   2.0
4   1.0   1.0  21.0   1.0   1.0   4.0  ...   2.0   2.0   2.0   1.0  1.0   2.0

[5 rows x 25 columns]
   V123  V125  V249  V290  V124  V191  ...   V3   V7  V170  V187  V37  id_06
0   1.0   1.0  21.0   1.0   1.0   4.0  ...  2.0  2.0   1.0   2.0  2.0  -89.0
1   1.0   1.0  21.0   1.0   1.0   4.0  ...  1.0  1.0   4.0   2.0  1.0  -89.0
2   1.0   1.0  21.0   2.0   1.0   4.0  ...  2.0  1.0   4.0   2.0  2.0  -61.0
3   1.0   1.0  21.0   1.0   1.0   4.0  ...  1.0  1.0   4.0   2.0  1.0  -89.0
4   1.0   1.0  21.0   1.0   1.0   4.0  ...  1.0  1.0   4.0   2.0  1.0  -89.0

[5 rows x 50 columns]
   V123  V125  V249  V29

In [0]:
train_features=[]
train_target=[]
test_features=[]
test_target=[]
for i in range(len(MI_TOP_0)):
  X_train_0,X_test_0,Y_train_0,Y_test_0=get_kfolds(2,MI_TOP_0[i],target_isFraud_0)
  X_train_1,X_test_1,Y_train_1,Y_test_1=get_kfolds(2,MI_TOP_1[i],target_isFraud_1)
  for j in range(len(X_train_0)):
    tr_features = pd.concat([pd.DataFrame(X_train_0[j]), pd.DataFrame(X_train_1[j])], axis=0)
    tr_target = pd.concat([pd.DataFrame(Y_train_0[j]), pd.DataFrame(Y_train_1[j])], axis=0)
    te_features = pd.concat([pd.DataFrame(X_test_0[j]), pd.DataFrame(X_test_1[j])], axis=0)
    te_target = pd.concat([pd.DataFrame(Y_test_0[j]), pd.DataFrame(Y_test_1[j])], axis=0)
    X = np.array(tr_features)
    y = np.array(tr_target)
    sm = SMOTE(random_state=2)
    X_res, y_res = sm.fit_sample(X, y)
    #print("Number transactions X dataset: ", X.shape)
    #print("Number transactions y dataset: ", y.shape)
    #print("Number transactions X_res dataset: ", X_res.shape)
    #print("Number transactions y_res dataset: ", y_res.shape)
    #print("Before OverSampling, counts of label '1': {}".format(sum(y==1)))
    #print("Before OverSampling, counts of label '0': {} \n".format(sum(y==0)))
    #print("After OverSampling, counts of label '1': {}".format(sum(y_res==1)))
    #print("After OverSampling, counts of label '0': {} \n".format(sum(y_res==0)))
    train_features.append(X_res)
    train_target.append(y_res)
    X_te = np.array(te_features)
    y_te = np.array(te_target)

    
    test_features.append(X_te)
    test_target.append(y_te)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

In [0]:
model = LogisticRegression()  # Choose a model here
for i in range(len(train_features)):
   model.fit(train_features[i], train_target[i] )
   y_pred = model.predict(test_features[i])
   print(f'Number of TOP MI: {train_features[i].shape[1]}')
   print(f'Number fold: {i}')

   f_score=f1_score(test_target[i], y_pred)
   cm = metrics.confusion_matrix(test_target[i], y_pred)
   print(cm)

   print(f'f-score: {f_score}')

   print(classification_report(test_target[i], y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 25
Number fold: 0
[[62770 22712]
 [ 1290  1810]]
f-score: 0.13105495619433782
              precision    recall  f1-score   support

           0       0.98      0.73      0.84     85482
           1       0.07      0.58      0.13      3100

    accuracy                           0.73     88582
   macro avg       0.53      0.66      0.49     88582
weighted avg       0.95      0.73      0.81     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 25
Number fold: 1
[[62868 22614]
 [ 1329  1770]]
f-score: 0.12880689881017354
              precision    recall  f1-score   support

           0       0.98      0.74      0.84     85482
           1       0.07      0.57      0.13      3099

    accuracy                           0.73     88581
   macro avg       0.53      0.65      0.48     88581
weighted avg       0.95      0.73      0.82     88581



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 50
Number fold: 2
[[63237 22245]
 [ 1228  1872]]
f-score: 0.13756108314656282
              precision    recall  f1-score   support

           0       0.98      0.74      0.84     85482
           1       0.08      0.60      0.14      3100

    accuracy                           0.74     88582
   macro avg       0.53      0.67      0.49     88582
weighted avg       0.95      0.74      0.82     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 50
Number fold: 3
[[63291 22191]
 [ 1241  1858]]
f-score: 0.1368793281273022
              precision    recall  f1-score   support

           0       0.98      0.74      0.84     85482
           1       0.08      0.60      0.14      3099

    accuracy                           0.74     88581
   macro avg       0.53      0.67      0.49     88581
weighted avg       0.95      0.74      0.82     88581



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 75
Number fold: 4
[[66704 18778]
 [ 1187  1913]]
f-score: 0.16081711571602705
              precision    recall  f1-score   support

           0       0.98      0.78      0.87     85482
           1       0.09      0.62      0.16      3100

    accuracy                           0.77     88582
   macro avg       0.54      0.70      0.52     88582
weighted avg       0.95      0.77      0.85     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 75
Number fold: 5
[[65574 19908]
 [ 1137  1962]]
f-score: 0.15715487204133124
              precision    recall  f1-score   support

           0       0.98      0.77      0.86     85482
           1       0.09      0.63      0.16      3099

    accuracy                           0.76     88581
   macro avg       0.54      0.70      0.51     88581
weighted avg       0.95      0.76      0.84     88581



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 100
Number fold: 6
[[69374 16108]
 [ 1068  2032]]
f-score: 0.1913370998116761
              precision    recall  f1-score   support

           0       0.98      0.81      0.89     85482
           1       0.11      0.66      0.19      3100

    accuracy                           0.81     88582
   macro avg       0.55      0.73      0.54     88582
weighted avg       0.95      0.81      0.87     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 100
Number fold: 7
[[69591 15891]
 [ 1101  1998]]
f-score: 0.19039451114922812
              precision    recall  f1-score   support

           0       0.98      0.81      0.89     85482
           1       0.11      0.64      0.19      3099

    accuracy                           0.81     88581
   macro avg       0.55      0.73      0.54     88581
weighted avg       0.95      0.81      0.87     88581



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 150
Number fold: 8
[[69887 15595]
 [ 1070  2030]]
f-score: 0.1958986731001206
              precision    recall  f1-score   support

           0       0.98      0.82      0.89     85482
           1       0.12      0.65      0.20      3100

    accuracy                           0.81     88582
   macro avg       0.55      0.74      0.54     88582
weighted avg       0.95      0.81      0.87     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 150
Number fold: 9
[[69537 15945]
 [ 1073  2026]]
f-score: 0.19231134314190793
              precision    recall  f1-score   support

           0       0.98      0.81      0.89     85482
           1       0.11      0.65      0.19      3099

    accuracy                           0.81     88581
   macro avg       0.55      0.73      0.54     88581
weighted avg       0.95      0.81      0.87     88581



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 200
Number fold: 10
[[68071 17411]
 [ 1146  1954]]
f-score: 0.1739594925439573
              precision    recall  f1-score   support

           0       0.98      0.80      0.88     85482
           1       0.10      0.63      0.17      3100

    accuracy                           0.79     88582
   macro avg       0.54      0.71      0.53     88582
weighted avg       0.95      0.79      0.86     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 200
Number fold: 11
[[65513 19969]
 [ 1149  1950]]
f-score: 0.1558877608122152
              precision    recall  f1-score   support

           0       0.98      0.77      0.86     85482
           1       0.09      0.63      0.16      3099

    accuracy                           0.76     88581
   macro avg       0.54      0.70      0.51     88581
weighted avg       0.95      0.76      0.84     88581



Testing on the real Test Data

In [0]:
real_test=pd.read_csv('gdrive/My Drive/Colab Notebooks/Predictive Modeling/DATA/3. fraud_remove_nulls_fill_random_distribution/test-fraud_remove_nulls_fill_random_distribution.csv',compression='gzip')

In [0]:
features_select=data[list(df_MI['Column'].head(150))]
test_features_select=real_test[list(df_MI['Column'].head(150))]

In [0]:
y_train=np.array(list(data['isFraud']))# .reshape(-1, 1)

In [0]:
X_train = np.array(features_select)

In [0]:
sm = SMOTE(random_state=2)

In [0]:
#sm = SMOTE(random_state=12, ratio = 1.0)
x_train_res, y_train_res = sm.fit_sample(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [0]:
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {} \n".format(sum(y_train_res==0)))

After OverSampling, counts of label '1': 170964
After OverSampling, counts of label '0': 170964 



In [0]:
y_real_test=np.array(list(real_test['isFraud'])) #.reshape(-1, 1)

In [0]:
X_real_test = np.array(test_features_select)

In [0]:
model = LogisticRegression()  # Choose a model here


In [0]:
model.fit(x_train_res, y_train_res )

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred = model.predict(X_real_test)

In [0]:
f_score=f1_score(y_real_test, y_pred)

In [0]:
print(f'f-score: {f_score}')

f-score: 0.19789201978920196


In [0]:

cm = metrics.confusion_matrix(y_real_test, y_pred)
print(cm)





[[139462  31502]
 [  2059   4140]]


In [0]:
print(classification_report(y_real_test, y_pred))


              precision    recall  f1-score   support

           0       0.99      0.82      0.89    170964
           1       0.12      0.67      0.20      6199

    accuracy                           0.81    177163
   macro avg       0.55      0.74      0.55    177163
weighted avg       0.96      0.81      0.87    177163

