In [0]:
#pip install --upgrade scikit-learn

In [0]:
from sklearn.feature_selection import mutual_info_classif
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from scipy.stats import chisquare
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
import csv
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

In [0]:
import matplotlib.pyplot as plt

In [0]:
from sklearn.metrics import f1_score

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import classification_report


In [0]:
#from sklearn.metrics import plot_confusion_matrix

ImportError: ignored

In [0]:
from imblearn.over_sampling import SMOTE

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [0]:
from google.colab import drive 
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
d=pd.read_csv('gdrive/My Drive/Colab Notebooks/Predictive Modeling/DATA/3. fraud_remove_nulls_fill_random_distribution/test-fraud_remove_nulls_fill_random_distribution.csv',compression='gzip')#2

In [0]:
data=d

In [0]:
from pandas.api.types import CategoricalDtype

# M1-M9: T/F/Blank
data['M1']=data['M1'].astype(CategoricalDtype(categories=['F','T']))
data['M1'] = data.M1.cat.codes
data['M2']=data['M2'].astype(CategoricalDtype(categories=['F','T']))
data['M2'] = data.M2.cat.codes
data['M3']=data['M3'].astype(CategoricalDtype(categories=['F','T']))
data['M3'] = data.M3.cat.codes

data['M4']=data['M4'].astype(CategoricalDtype(categories=['M0','M1','M2']))
data['M4'] = data.M4.cat.codes

data['M5']=data['M5'].astype(CategoricalDtype(categories=['F','T']))
data['M5'] = data.M5.cat.codes
data['M6']=data['M6'].astype(CategoricalDtype(categories=['F','T']))
data['M6'] = data.M6.cat.codes
data['M7']=data['M7'].astype(CategoricalDtype(categories=['F','T']))
data['M7'] = data.M7.cat.codes
data['M8']=data['M8'].astype(CategoricalDtype(categories=['F','T']))
data['M8'] = data.M8.cat.codes
data['M9']=data['M9'].astype(CategoricalDtype(categories=['F','T']))
data['M9'] = data.M9.cat.codes

data['ProductCD']=data['ProductCD'].astype(CategoricalDtype())
data['ProductCD'] = data.ProductCD.cat.codes

data['device_name']=data['device_name'].astype(CategoricalDtype())
data['device_name'] = data.device_name.cat.codes

data['DeviceType']=data['DeviceType'].astype(CategoricalDtype())
data['DeviceType'] = data.DeviceType.cat.codes

data['addr1']=data['addr1'].astype(CategoricalDtype())
data['addr1'] = data.addr1.cat.codes
data['addr2']=data['addr2'].astype(CategoricalDtype())
data['addr2'] = data.addr2.cat.codes

data['card1']=data['card1'].astype(CategoricalDtype())
data['card1'] = data.card1.cat.codes
data['card2']=data['card2'].astype(CategoricalDtype())
data['card2'] = data.card2.cat.codes
data['card3']=data['card3'].astype(CategoricalDtype())
data['card3'] = data.card3.cat.codes
data['card4']=data['card4'].astype(CategoricalDtype())
data['card4'] = data.card4.cat.codes
data['card5']=data['card5'].astype(CategoricalDtype())
data['card5'] = data.card5.cat.codes
data['card6']=data['card6'].astype(CategoricalDtype())
data['card6'] = data.card6.cat.codes

data['P_emaildomain_bin']=data['P_emaildomain_bin'].astype(CategoricalDtype())
data['P_emaildomain_bin'] = data.P_emaildomain_bin.cat.codes
data['R_emaildomain_bin']=data['R_emaildomain_bin'].astype(CategoricalDtype())
data['R_emaildomain_bin'] = data.R_emaildomain_bin.cat.codes
data['P_emaildomain_suffix']=data['P_emaildomain_suffix'].astype(CategoricalDtype())
data['P_emaildomain_suffix'] = data.P_emaildomain_suffix.cat.codes
data['R_emaildomain_suffix']=data['R_emaildomain_suffix'].astype(CategoricalDtype())
data['R_emaildomain_suffix'] = data.R_emaildomain_suffix.cat.codes

data['_Month']=data['_Month'].astype(CategoricalDtype())
data['_Month'] = data._Month.cat.codes
data['_Weekdays']=data['_Weekdays'].astype(CategoricalDtype())
data['_Weekdays'] = data._Weekdays.cat.codes
data['_Hours']=data['_Hours'].astype(CategoricalDtype())
data['_Hours'] = data._Hours.cat.codes
data['_Days']=data['_Days'].astype(CategoricalDtype())
data['_Days'] = data._Days.cat.codes

data['id_12']=data['id_12'].astype(CategoricalDtype())
data['id_12'] = data.id_12.cat.codes 
data['id_13']=data['id_13'].astype(CategoricalDtype())
data['id_13'] = data.id_13.cat.codes 
data['id_15']=data['id_15'].astype(CategoricalDtype())
data['id_15'] = data.id_15.cat.codes 
data['id_16']=data['id_16'].astype(CategoricalDtype())
data['id_16'] = data.id_16.cat.codes 
data['id_17']=data['id_17'].astype(CategoricalDtype())
data['id_17'] = data.id_17.cat.codes 
data['id_19']=data['id_19'].astype(CategoricalDtype())
data['id_19'] = data.id_19.cat.codes 
data['id_20']=data['id_20'].astype(CategoricalDtype())
data['id_20'] = data.id_20.cat.codes
data['id_28']=data['id_28'].astype(CategoricalDtype())
data['id_28'] = data.id_28.cat.codes
data['id_29']=data['id_29'].astype(CategoricalDtype())
data['id_29'] = data.id_29.cat.codes
data['id_31']=data['id_31'].astype(CategoricalDtype())
data['id_31'] = data.id_31.cat.codes
data['id_35']=data['id_35'].astype(CategoricalDtype())
data['id_35'] = data.id_35.cat.codes
data['id_36']=data['id_36'].astype(CategoricalDtype())
data['id_36'] = data.id_36.cat.codes
data['id_37']=data['id_37'].astype(CategoricalDtype())
data['id_37'] = data.id_37.cat.codes
data['id_38']=data['id_38'].astype(CategoricalDtype())
data['id_38'] = data.id_38.cat.codes

In [0]:
#To change file name uploaded
df_MI=pd.read_csv('gdrive/My Drive/Colab Notebooks/Predictive Modeling/DATA/3. fraud_remove_nulls_fill_random_distribution/features_MI_train-remove_nulls_fill_random_distribution.csv')

In [0]:
features_25=data[list(df_MI['Column'].head(25))]
features_50=data[list(df_MI['Column'].head(50))]
features_75=data[list(df_MI['Column'].head(75))]
features_100=data[list(df_MI['Column'].head(100))]
features_150=data[list(df_MI['Column'].head(150))]
features_200=data[list(df_MI['Column'].head(200))]

In [0]:
features_25.shape

(10000, 25)

Spliting the data into features and target for isFraud=0 and isFraud=1

In [0]:
data_isFraud_1_indexes=list(data[data['isFraud']==1].index)
data_isFraud_0_indexes=list(data[data['isFraud']==0].index)
data_isFraud_1=data.iloc[data_isFraud_1_indexes , : ]
data_isFraud_0=data.iloc[data_isFraud_0_indexes , : ]

target_isFraud_1=data_isFraud_1['isFraud']
print('target_isFraurd_1 shape: ',target_isFraud_1.shape)

features_isFraud_1=data_isFraud_1.drop(['isFraud'],axis=1)
print('features_isFraud_1 shape: ',features_isFraud_1.shape)

target_isFraud_0=data_isFraud_0['isFraud']
print('target_isFraurd_0 shape: ',target_isFraud_0.shape)

features_isFraud_0=data_isFraud_0.drop(['isFraud'],axis=1)
print('features_isFraud_0 shape: ',features_isFraud_0.shape)

target_isFraurd_1 shape:  (6199,)
features_isFraud_1 shape:  (6199, 364)
target_isFraurd_0 shape:  (170964,)
features_isFraud_0 shape:  (170964, 364)


In [0]:
features_25_0=features_isFraud_0[list(df_MI['Column'].head(25))]
features_50_0=features_isFraud_0[list(df_MI['Column'].head(50))]
features_75_0=features_isFraud_0[list(df_MI['Column'].head(75))]
features_100_0=features_isFraud_0[list(df_MI['Column'].head(100))]
features_150_0=features_isFraud_0[list(df_MI['Column'].head(150))]
features_200_0=features_isFraud_0[list(df_MI['Column'].head(200))]

In [0]:
features_25_0.shape

(10000, 25)

In [0]:
features_25_1=features_isFraud_1[list(df_MI['Column'].head(25))]
features_50_1=features_isFraud_1[list(df_MI['Column'].head(50))]
features_75_1=features_isFraud_1[list(df_MI['Column'].head(75))]
features_100_1=features_isFraud_1[list(df_MI['Column'].head(100))]
features_150_1=features_isFraud_1[list(df_MI['Column'].head(150))]
features_200_1=features_isFraud_1[list(df_MI['Column'].head(200))]

In [0]:
features_25_1.shape

In [0]:
from sklearn.model_selection import KFold

In [0]:
def get_kfolds(splits,features,target):
  kf = KFold(n_splits=splits)

  X=features
  Y=target

  X_train_base=[]
  X_test_base=[]
  Y_train_base=[]
  Y_test_base=[]

  for train_index, test_index in kf.split(X):
      #print('train_index', train_index)
      #print('test_index', test_index)
      X_train, X_test = X.iloc[train_index,:], X.iloc[test_index,:]
      Y_train, Y_test = Y.iloc[train_index], Y.iloc[test_index]
      X_train_base.append(X_train)
      X_test_base.append(X_test)
      Y_train_base.append(Y_train)
      Y_test_base.append(Y_test)
  
  return(X_train_base,X_test_base,Y_train_base,Y_test_base)
  



In [0]:
MI_TOP_0=[features_25_0,features_50_0,features_75_0,features_100_0,features_150_0,features_200_0]


In [0]:
MI_TOP_1=[features_25_1,features_50_1,features_75_1,features_100_1,features_150_1,features_200_1]


In [0]:
train_features=[]
train_target=[]
test_features=[]
test_target=[]
for i in range(len(MI_TOP_0)):
  X_train_0,X_test_0,Y_train_0,Y_test_0=get_kfolds(2,MI_TOP_0[i],target_isFraud_0)
  X_train_1,X_test_1,Y_train_1,Y_test_1=get_kfolds(2,MI_TOP_1[i],target_isFraud_1)
  for j in range(len(X_train_0)):
    tr_features = pd.concat([pd.DataFrame(X_train_0[j]), pd.DataFrame(X_train_1[j])], axis=0)
    tr_target = pd.concat([pd.DataFrame(Y_train_0[j]), pd.DataFrame(Y_train_1[j])], axis=0)
    te_features = pd.concat([pd.DataFrame(X_test_0[j]), pd.DataFrame(X_test_1[j])], axis=0)
    te_target = pd.concat([pd.DataFrame(Y_test_0[j]), pd.DataFrame(Y_test_1[j])], axis=0)
    X = np.array(tr_features)
    y = np.array(tr_target)
    sm = SMOTE(random_state=2)
    X_res, y_res = sm.fit_sample(X, y)
    #print("Number transactions X dataset: ", X.shape)
    #print("Number transactions y dataset: ", y.shape)
    #print("Number transactions X_res dataset: ", X_res.shape)
    #print("Number transactions y_res dataset: ", y_res.shape)
    #print("Before OverSampling, counts of label '1': {}".format(sum(y==1)))
    #print("Before OverSampling, counts of label '0': {} \n".format(sum(y==0)))
    #print("After OverSampling, counts of label '1': {}".format(sum(y_res==1)))
    #print("After OverSampling, counts of label '0': {} \n".format(sum(y_res==0)))
    train_features.append(X_res)
    train_target.append(y_res)
    X_te = np.array(te_features)
    y_te = np.array(te_target)

    
    test_features.append(X_te)
    test_target.append(y_te)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

In [0]:
model = LogisticRegression()  # Choose a model here
for i in range(len(train_features)):
   model.fit(train_features[i], train_target[i] )
   y_pred = model.predict(test_features[i])
   print(f'Number of TOP MI: {train_features[i].shape[1]}')
   print(f'Number fold: {i}')

   f_score=f1_score(test_target[i], y_pred)
   cm = metrics.confusion_matrix(test_target[i], y_pred)
   print(cm)

   print(f'f-score: {f_score}')

   print(classification_report(test_target[i], y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 25
Number fold: 0
[[62770 22712]
 [ 1290  1810]]
f-score: 0.13105495619433782
              precision    recall  f1-score   support

           0       0.98      0.73      0.84     85482
           1       0.07      0.58      0.13      3100

    accuracy                           0.73     88582
   macro avg       0.53      0.66      0.49     88582
weighted avg       0.95      0.73      0.81     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 25
Number fold: 1
[[62868 22614]
 [ 1329  1770]]
f-score: 0.12880689881017354
              precision    recall  f1-score   support

           0       0.98      0.74      0.84     85482
           1       0.07      0.57      0.13      3099

    accuracy                           0.73     88581
   macro avg       0.53      0.65      0.48     88581
weighted avg       0.95      0.73      0.82     88581



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 50
Number fold: 2
[[63237 22245]
 [ 1228  1872]]
f-score: 0.13756108314656282
              precision    recall  f1-score   support

           0       0.98      0.74      0.84     85482
           1       0.08      0.60      0.14      3100

    accuracy                           0.74     88582
   macro avg       0.53      0.67      0.49     88582
weighted avg       0.95      0.74      0.82     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 50
Number fold: 3
[[63291 22191]
 [ 1241  1858]]
f-score: 0.1368793281273022
              precision    recall  f1-score   support

           0       0.98      0.74      0.84     85482
           1       0.08      0.60      0.14      3099

    accuracy                           0.74     88581
   macro avg       0.53      0.67      0.49     88581
weighted avg       0.95      0.74      0.82     88581



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Number of TOP MI: 75
Number fold: 4
[[66704 18778]
 [ 1187  1913]]
f-score: 0.16081711571602705
              precision    recall  f1-score   support

           0       0.98      0.78      0.87     85482
           1       0.09      0.62      0.16      3100

    accuracy                           0.77     88582
   macro avg       0.54      0.70      0.52     88582
weighted avg       0.95      0.77      0.85     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 75
Number fold: 5
[[65574 19908]
 [ 1137  1962]]
f-score: 0.15715487204133124
              precision    recall  f1-score   support

           0       0.98      0.77      0.86     85482
           1       0.09      0.63      0.16      3099

    accuracy                           0.76     88581
   macro avg       0.54      0.70      0.51     88581
weighted avg       0.95      0.76      0.84     88581



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 100
Number fold: 6
[[69374 16108]
 [ 1068  2032]]
f-score: 0.1913370998116761
              precision    recall  f1-score   support

           0       0.98      0.81      0.89     85482
           1       0.11      0.66      0.19      3100

    accuracy                           0.81     88582
   macro avg       0.55      0.73      0.54     88582
weighted avg       0.95      0.81      0.87     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 100
Number fold: 7
[[69591 15891]
 [ 1101  1998]]
f-score: 0.19039451114922812
              precision    recall  f1-score   support

           0       0.98      0.81      0.89     85482
           1       0.11      0.64      0.19      3099

    accuracy                           0.81     88581
   macro avg       0.55      0.73      0.54     88581
weighted avg       0.95      0.81      0.87     88581



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 150
Number fold: 8
[[69887 15595]
 [ 1070  2030]]
f-score: 0.1958986731001206
              precision    recall  f1-score   support

           0       0.98      0.82      0.89     85482
           1       0.12      0.65      0.20      3100

    accuracy                           0.81     88582
   macro avg       0.55      0.74      0.54     88582
weighted avg       0.95      0.81      0.87     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 150
Number fold: 9
[[69537 15945]
 [ 1073  2026]]
f-score: 0.19231134314190793
              precision    recall  f1-score   support

           0       0.98      0.81      0.89     85482
           1       0.11      0.65      0.19      3099

    accuracy                           0.81     88581
   macro avg       0.55      0.73      0.54     88581
weighted avg       0.95      0.81      0.87     88581



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 200
Number fold: 10
[[68071 17411]
 [ 1146  1954]]
f-score: 0.1739594925439573
              precision    recall  f1-score   support

           0       0.98      0.80      0.88     85482
           1       0.10      0.63      0.17      3100

    accuracy                           0.79     88582
   macro avg       0.54      0.71      0.53     88582
weighted avg       0.95      0.79      0.86     88582



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Number of TOP MI: 200
Number fold: 11
[[65513 19969]
 [ 1149  1950]]
f-score: 0.1558877608122152
              precision    recall  f1-score   support

           0       0.98      0.77      0.86     85482
           1       0.09      0.63      0.16      3099

    accuracy                           0.76     88581
   macro avg       0.54      0.70      0.51     88581
weighted avg       0.95      0.76      0.84     88581



Testing on the real Test Data

In [0]:
real_test=pd.read_csv('gdrive/My Drive/Colab Notebooks/Predictive Modeling/DATA/3. fraud_remove_nulls_fill_random_distribution/test-fraud_remove_nulls_fill_random_distribution.csv',compression='gzip')

In [0]:
from pandas.api.types import CategoricalDtype

# M1-M9: T/F/Blank
real_test['M1']=real_test['M1'].astype(CategoricalDtype(categories=['F','T']))
real_test['M1'] = real_test.M1.cat.codes
real_test['M2']=real_test['M2'].astype(CategoricalDtype(categories=['F','T']))
real_test['M2'] = real_test.M2.cat.codes
real_test['M3']=real_test['M3'].astype(CategoricalDtype(categories=['F','T']))
real_test['M3'] = real_test.M3.cat.codes

real_test['M4']=real_test['M4'].astype(CategoricalDtype(categories=['M0','M1','M2']))
real_test['M4'] = real_test.M4.cat.codes

real_test['M5']=real_test['M5'].astype(CategoricalDtype(categories=['F','T']))
real_test['M5'] = real_test.M5.cat.codes
real_test['M6']=real_test['M6'].astype(CategoricalDtype(categories=['F','T']))
real_test['M6'] = real_test.M6.cat.codes
real_test['M7']=real_test['M7'].astype(CategoricalDtype(categories=['F','T']))
real_test['M7'] = real_test.M7.cat.codes
real_test['M8']=real_test['M8'].astype(CategoricalDtype(categories=['F','T']))
real_test['M8'] = real_test.M8.cat.codes
real_test['M9']=real_test['M9'].astype(CategoricalDtype(categories=['F','T']))
real_test['M9'] = real_test.M9.cat.codes

real_test['ProductCD']=real_test['ProductCD'].astype(CategoricalDtype())
real_test['ProductCD'] = real_test.ProductCD.cat.codes

real_test['device_name']=real_test['device_name'].astype(CategoricalDtype())
real_test['device_name'] = real_test.device_name.cat.codes

real_test['DeviceType']=real_test['DeviceType'].astype(CategoricalDtype())
real_test['DeviceType'] = real_test.DeviceType.cat.codes

real_test['addr1']=real_test['addr1'].astype(CategoricalDtype())
real_test['addr1'] = real_test.addr1.cat.codes
real_test['addr2']=real_test['addr2'].astype(CategoricalDtype())
real_test['addr2'] = real_test.addr2.cat.codes

real_test['card1']=real_test['card1'].astype(CategoricalDtype())
real_test['card1'] = real_test.card1.cat.codes
real_test['card2']=real_test['card2'].astype(CategoricalDtype())
real_test['card2'] = real_test.card2.cat.codes
real_test['card3']=real_test['card3'].astype(CategoricalDtype())
real_test['card3'] = real_test.card3.cat.codes
real_test['card4']=real_test['card4'].astype(CategoricalDtype())
real_test['card4'] = real_test.card4.cat.codes
real_test['card5']=real_test['card5'].astype(CategoricalDtype())
real_test['card5'] = real_test.card5.cat.codes
real_test['card6']=real_test['card6'].astype(CategoricalDtype())
real_test['card6'] = real_test.card6.cat.codes

real_test['P_emaildomain_bin']=real_test['P_emaildomain_bin'].astype(CategoricalDtype())
real_test['P_emaildomain_bin'] = real_test.P_emaildomain_bin.cat.codes
real_test['R_emaildomain_bin']=real_test['R_emaildomain_bin'].astype(CategoricalDtype())
real_test['R_emaildomain_bin'] = real_test.R_emaildomain_bin.cat.codes
real_test['P_emaildomain_suffix']=real_test['P_emaildomain_suffix'].astype(CategoricalDtype())
real_test['P_emaildomain_suffix'] = real_test.P_emaildomain_suffix.cat.codes
real_test['R_emaildomain_suffix']=real_test['R_emaildomain_suffix'].astype(CategoricalDtype())
real_test['R_emaildomain_suffix'] = real_test.R_emaildomain_suffix.cat.codes

real_test['_Month']=real_test['_Month'].astype(CategoricalDtype())
real_test['_Month'] = real_test._Month.cat.codes
real_test['_Weekdays']=real_test['_Weekdays'].astype(CategoricalDtype())
real_test['_Weekdays'] = real_test._Weekdays.cat.codes
real_test['_Hours']=real_test['_Hours'].astype(CategoricalDtype())
real_test['_Hours'] = real_test._Hours.cat.codes
real_test['_Days']=real_test['_Days'].astype(CategoricalDtype())
real_test['_Days'] = real_test._Days.cat.codes

real_test['id_12']=real_test['id_12'].astype(CategoricalDtype())
real_test['id_12'] = real_test.id_12.cat.codes 
real_test['id_13']=real_test['id_13'].astype(CategoricalDtype())
real_test['id_13'] = real_test.id_13.cat.codes 
real_test['id_15']=real_test['id_15'].astype(CategoricalDtype())
real_test['id_15'] = real_test.id_15.cat.codes 
real_test['id_16']=real_test['id_16'].astype(CategoricalDtype())
real_test['id_16'] = real_test.id_16.cat.codes 
real_test['id_17']=real_test['id_17'].astype(CategoricalDtype())
real_test['id_17'] = real_test.id_17.cat.codes 
real_test['id_19']=real_test['id_19'].astype(CategoricalDtype())
real_test['id_19'] = real_test.id_19.cat.codes 
real_test['id_20']=real_test['id_20'].astype(CategoricalDtype())
real_test['id_20'] = real_test.id_20.cat.codes
real_test['id_28']=real_test['id_28'].astype(CategoricalDtype())
real_test['id_28'] = real_test.id_28.cat.codes
real_test['id_29']=real_test['id_29'].astype(CategoricalDtype())
real_test['id_29'] = real_test.id_29.cat.codes
real_test['id_31']=real_test['id_31'].astype(CategoricalDtype())
real_test['id_31'] = real_test.id_31.cat.codes
real_test['id_35']=real_test['id_35'].astype(CategoricalDtype())
real_test['id_35'] = real_test.id_35.cat.codes
real_test['id_36']=real_test['id_36'].astype(CategoricalDtype())
real_test['id_36'] = real_test.id_36.cat.codes
real_test['id_37']=real_test['id_37'].astype(CategoricalDtype())
real_test['id_37'] = real_test.id_37.cat.codes
real_test['id_38']=real_test['id_38'].astype(CategoricalDtype())
real_test['id_38'] = real_test.id_38.cat.codes



In [0]:
features_select=data[list(df_MI['Column'].head(150))]
test_features_select=real_test[list(df_MI['Column'].head(150))]

In [0]:
y_train=np.array(list(data['isFraud']))# .reshape(-1, 1)

In [0]:
X_train = np.array(features_select)

In [0]:
sm = SMOTE(random_state=2)

In [0]:
#sm = SMOTE(random_state=12, ratio = 1.0)
x_train_res, y_train_res = sm.fit_sample(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [0]:
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {} \n".format(sum(y_train_res==0)))

After OverSampling, counts of label '1': 170964
After OverSampling, counts of label '0': 170964 



In [0]:
y_real_test=np.array(list(real_test['isFraud'])) #.reshape(-1, 1)

In [0]:
X_real_test = np.array(test_features_select)

In [0]:
model = LogisticRegression()  # Choose a model here


In [0]:
model.fit(x_train_res, y_train_res )

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred = model.predict(X_real_test)

In [0]:
f_score=f1_score(y_real_test, y_pred)

In [0]:
print(f'f-score: {f_score}')

f-score: 0.19789201978920196


In [0]:

cm = metrics.confusion_matrix(y_real_test, y_pred)
print(cm)





[[139462  31502]
 [  2059   4140]]


In [0]:
print(classification_report(y_real_test, y_pred))


              precision    recall  f1-score   support

           0       0.99      0.82      0.89    170964
           1       0.12      0.67      0.20      6199

    accuracy                           0.81    177163
   macro avg       0.55      0.74      0.55    177163
weighted avg       0.96      0.81      0.87    177163

